devops/devops/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
]

devops/hello/urls.py
from django.urls import path, re_path
from . import views

app_name = 'hello'
urlpatterns = [
    path('', views.index, name = 'index'),
    #path('list/', views.index, name='list'),
    #re_path('([0-9]{4})/([0-9]{2})/', views.index, name='index')
    #re_path('(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/', views.index, name='index')
    path('list/' ,views.list ,name = 'list' ),
    path('userlist/' ,views.userlist_work ,name ='userlist_work' ),
    path('userlist/useradd/' ,views.useradd ,name = "useradd"),
    #path('userlist/add', views.add, name = 'add'),
    path('userlist/<int:id>/mod' ,views.mod ,name = 'mod'),
    path('userlist/<int:id>/delete' ,views.delete ,name = 'delete'),
    #path('userlist/addaction/' ,views.addaction ,name = "addaction"),
    path('userlist/<int:id>/deleaction/' ,views.deleaction ,name = "deleaction"),
    path('userlist/<int:id>/modaction/' ,views.modaction ,name = "modaction"),
]

devops/hello/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    SEX = (
        ('0' ,'男'),
        ('1' ,'女'),
    )
    name = models.CharField(max_length= 20 ,
                            help_text="用户名")
    password = models.CharField(max_length= 32 ,help_text="密码")

    sex = models.IntegerField(choices = SEX ,null=True, blank=True)

    def __str__(self):
        return self.name

devops/hello/views.py
import traceback

from django.shortcuts import render
from django.http import  HttpResponse, QueryDict
#from hello.models import User
from django.shortcuts import render
from django.contrib import messages
from .models import User
import sys

# def index(request, **kwargs):
#     #return HttpResponse("<p>Hello world,Hello,Django</p>")
#     #year = request.GET.get("year", "2020")
#     #month = request.GET.get("month", "03")
#     print(kwargs)
#     year = kwargs.get("year")
#     month = kwargs.get("month")
#     return HttpResponse("year is %s, month is %s" %(year, month))
# Create your views here.
# def index(request, month, year):
#     return HttpResponse("year is %s ,month is %s "% (year, month))

# def index(request):
#     print('=' * 30)
#     print(request.scheme)
#     print(request.method)
#     print(request.headers)
#     print(request.path)
#     print(request.META)
#     print(request.GET)
#     data = request.GET
#     year = data.get("year", "2019")
#     month = data.get("month", "10")
#     if request.method == "POST":
#         print("@" * 30)
#         print(request.method)
#         print(request.body)
#         print(QueryDict(request.body).dict())
#         print(request.POST)
#         data = request.POST
#         year = data.get("year", "2020")
#         print("*" * 30)
#         month = data.get("month", "04")
#         print(year)
#         print(month)
#     return HttpResponse("year is %s, month is %s" % (year, month))

def index(request):
    classname = "DevOps"
    books = ['Python', 'Java', 'Django']
    user = {'name': 'kk', 'age': 18}
    userlist = [{'name': 'kk', 'age': 18}, {'name': 'rock', 'age': 19},
                {'name': 'mage', 'age': 20}]
    return render(request, 'hello/hello.html', {'classname': classname, "books": books, "user":user, "userlist": userlist})

def list(request):
    value = ['python','django','java']
    messages = ['1','2','3','4','5']
    users = [
        {"username": 'kk1', 'name_cn': 'kk1', 'age': 18},
        {"username": 'kk2', 'name_cn': 'kk2', 'age': 19},
        {"username": 'kk3', 'name_cn': 'kk3', 'age': 20},
    ]
    print("=" * 30 )
    print(users)
    return render(request, 'hello/userlist.html', {'users': users , 'messages':messages , 'value':value})

def userlist_work(request):
    # result = User.objects.all()
    # print("=" * 30 )
    # print(result)
    # # data = {'name': 't1','password': '123'}
    # # result.objects.create(**data)
    # # u = User()
    # # u.name = 'kk'
    # # u.password = '123'
    # # u.save()
    # print(result)
    # return render(request, 'hello/userlist_work.html', {'users': result})
    keyword = request.GET.get("keyword","")
    users = User.objects.all()
    if keyword:
        users = users.filter(name_icontains=keyword)
    print(users)
    return render(request,'hello/userlist_work.html' ,{"users":users ,"keyword":keyword})

# def add(request):
#     return render(request ,'hello/add.html')
#
# def addaction(request):
#     print("="*30)
#     print(request.POST)
#     data = request.POST
#     name = data.get("name")
#     password = data.get("password")
#     sex = data.get("sex")
#     User.objects.create(**data)
#     return render(request ,'hello/addaction.html')

def useradd(request):    #改进版，将add代码复用
    msg = {}
    print("调用useradd")
    print(request.method)
    if request.method == "POST":
        try:
            data = request.POST.dict()  #将提交的数据转为字典，一次性入库
            print("useradd测试")
            print(type(data),data)
            #data.pop('csrfmiddlewaretoken')  #pop掉字典中的csrf
            User.objects.create(**data)
            print(User.objects.all)
            msg = {"code" :0 ,"result":"添加用户成功"}
        except:
            print("ERROR")
            msg = {"code" :1 ,"errmsg":"添加用户失败：%s" % traceback.format_exc()}
    return render(request ,"hello/add.html" ,{ "msg" : msg })


def mod(request ,id):
    user = User.objects.all().filter(id=id)
    print(type(id))
    return render(request ,'hello/mod.html', {'user': user})

def modaction(request ,id):
    print(request.POST)
    data = request.POST
    name = data.get("name")
    password = data.get("password")
    sex = data.get("sex")
    print(id,name,password)
    u = User.objects.all()
    print(u)
    User.objects.filter(id=id).update(name=name ,password=password ,sex=sex)
    return render(request, 'hello/modaction.html' ,{'user': name})

def delete(requeset ,id):
    print(type(id))
    user = User.objects.all().filter(id=id)
    print(type(requeset))
    print(type(user),user)
    return render(requeset ,'hello/delete.html', {'user': user})

def deleaction(request ,id):
    User.objects.filter(id=id).delete()
    return render(request, 'hello/deleaction.html')

devops/templates/hello/add.html
{% extends "./base.html" %}

{% block content %}
{% if msg.code == 0 %}
    <p style="color: green">{{ msg.result }}</p>
{% else %}
    <p style="color: red">{{ msg.errmsg }}</p>
{% endif %}
    <form action="" method="post">
<!--        403 Forbidden."CSRF token missing or incorrect"响应的处理解决方法-->
<!--        setting 中 注释'django.middleware.csrf.CsrfViewMiddleware',解决-->
<!--        {% csrf_token %}-->
        姓名:
        <input type="text" name="name">
        <br>
        <br>
        密码:
        <input type="password" name="password">
        <br>
        <br>
        性别:
        <input type="radio" name="sex" value="0" checked>男
        <input type="radio" name="sex" value="1" checked>女
        <br>
        <br>
        <input type="submit" value="提交">
    </form>

{% endblock %}

devops/templates/hello/addaction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% extends "./base.html" %}
</head>
<body>

</body>
</html>

devops/templates/hello/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自动化运维平台</title>
</head>
<body>
<p style="background-color: yellow">
    {% block title %} 用户管理系统 {% endblock  %}
</p>

   {% block content %}
   {% endblock %}
<p style="background-color: red">版权所有：刘华</p>

</body>
</html>


<!--<table border="1">-->
<!--   <thead>-->
<!--        <tr>-->
<!--            <th>用户名</th>-->
<!--            <th>姓名</th>-->
<!--            <th>年龄</th>-->
<!--        </tr>-->
<!--    </thead>-->
<!--<tbody>-->
<!--    {% for user in users %}-->
<!--    <tr>-->
<!--       <td>{{ user.username }}</td>-->
<!--        <td>{{ user.name_cn }}</td>-->
<!--        <td>{{ user.age }}</td>-->
<!--    </tr>-->
<!--    {% endfor %}-->
<!--</tbody>-->
<!--    </table>-->

devops/templates/hello/deleaction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "./base.html" %}
</head>
<body>

</body>
</html>

devops/templates/hello/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% extends "./base.html" %}
</head>
<body>
     {% block content %}
<h3>确定要删除以下用户吗？</h3>
<table border="1">
<thead>
    <tr>
        <th>ID</th>
        <th>姓名</th>
        <th>密码</th>
        <th>性别</th>
    </tr>
</thead>
<tbody>
    {% for u in user %}
    <tr>
        <td>{{ u.id }}</td>
        <td>{{ u.name }}</td>
        <td>{{ u.password }}</td>
        <td>{{ u.sex }}</td>
    </tr>
    {% endfor %}
</tbody>
</table>
<a href="javascript:history.go(-1)" >返回</a> <a href="deleaction" >确定</a>
{% endblock %}
</body>
</html>

<!--<table border="1">-->
<!--    <thead>-->
<!--        <tr>-->
<!--            <th>id</th>-->
<!--            <th>姓名</th>-->
<!--            <th>密码</th>-->
<!--            <th>性别</th>-->
<!--            <th>管理</th>-->
<!--    </thead>-->
<!--<tbody>-->
<!--    {% for user in users %}-->
<!--    <tr>-->
<!--        <td>{{ user.id }}</td>-->
<!--        <td>{{ user.name }}</td>-->
<!--        <td>{{ user.password }}</td>-->
<!--        <td>{{ user.sex }}</td>-->
<!--        <td><a href="{{ user.id }}/mod">编辑</a>  <a href="{{ user.id }}/delete">删除</a> </td>-->
<!--    </tr>-->
<!--    {% endfor %}-->

devops/templates/hello/hello.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Devops</title>-->
<!--</head>-->
<!--<body>-->
<p style="background-color: yellow;">hello Django</p>
<p style="background-color: blue;">classname</p>
<p style="background-color: blue;">{{classname}},{{books}}</p>
<li>{{ books.0 }}</li>>

<div  color = blue>hello my name is {{ user.name }} </br>
    my age is {{ user.age }}
</div>
{% for user in userlist %}
<li>{{ user.name }} -->{{ user.age }}</li>
{% endfor %}

{% if user %}
<p> name:{{ user.name }} </p>
{% else %}
    用户名不存在
{% endif %}


<!--</body>-->
<!--</html>-->

<!--<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">-->
<!--<head>-->
<!--<meta http-equiv="Content-Type" content="text/html;charset=UTF- -->
<!--8" />-->
<!--<title>DevOps</title>-->
<!--<head>-->
<!--<body>-->
<!--<p> {{ name }} </p> {#接受视图中的一般变量量值#}-->
<!--<li>{{ books.0 }}</li> {# 接受列表中的值#}-->
<!--<li>{{ books.1 }}</li>-->
<!--<li>{{ books.2 }}</li>-->
<!--{# 接受字典中的定义的值 #}-->
<!--<div color = blue>hello my name is {{ user.name }} </br>-->
<!--my age is {{ user.age }}-->
<!--</div>{# if标签使用，判断user是否存在 #}-->
<!--{% if user %}-->
<!--<p> name:{{ user.name }} </p>-->
<!--{%else%}-->
<!--用户不存在-->
<!--{% endif %}-->
<!--{# for循环标签，渲染books列表 #}-->
<!--{% for book in books %}-->
<!--<li>{{ book }}</li>-->
<!--{% endfor %}-->
<!--{# for循环输出列表嵌套字典数据 #}-->
<!--{% for user in userlist %}-->
<!--<li>{{ user.name }}&ndash;&gt;{{ user.age }}</li>-->
<!--{% endfor %}-->
<!--</body>-->
<!--</html>-->

devops/templates/hello/mod.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "./base.html" %}

    {% block content %}
<table border="1">
<thead>
    <tr>
        <th>ID</th>
        <th>姓名</th>
        <th>密码</th>
        <th>性别</th>
    </tr>
</thead>
<tbody>
    {% for u in user %}
    <tr>
        <td>{{ u.id }}</td>
        <td>{{ u.name }}</td>
        <td>{{ u.password }}</td>
        <td>{{ u.sex }}</td>
    </tr>

    {% endfor %}
</tbody>
</table>
<h4>编辑用户：</h4>
    <form action="modaction/" method="post">
<!--        403 Forbidden."CSRF token missing or incorrect"响应的处理解决方法-->
        {% csrf_token %}
        name:<br>
        <input type="text" name="name">
        <br>
        password:<br>
        <input type="text" name="password">
        <br>
        sex:<br>
        <input type="text" name="sex">
        <br><br>
        <input type="submit" value="提交">
    </form>

{% endblock %}

</head>
<body>

</body>
</html>

devops/templates/hello/modaction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "./base.html" %}
    {% block content %}
<p> 用户：{{ user }} 的信息已修改成功！ </p>
{% endblock %}
</head>
<body>

</body>
</html>

devops/templates/hello/userlist.html
{% extends "./base.html" %}

{% block title %} 用户的列表 {% endblock %}

{% block content %}
<table border="1">
    <thead>
        <tr>
            <th>用户名</th>
            <th>姓名</th>
            <th>年龄</th>
        </tr>
    </thead>
<tbody>
    {% for user in users %}
    <tr>
        <td>{{ user.username }}</td>
        <td>{{ user.name_cn }}</td>
        <td>{{ user.age }}</td>
    </tr>
    {% endfor %}
</tbody>
</table>
{% if messages|length >= 3 %}
    You have lots of messages today!
{% else %}
    You have not messages today!
{% endif %}
<br>
{{ value|default:"nothing" }}
<br>
{{value|length}}
<br>
{{ value|join:',' }}
<br>
{{ value|slice:"1"}}
<br>
{% load mytag %}
# 管道符前面为第一个参数，后面为第二个参数
<p>{{ "3" | test:'3' }}</p>

{% endblock %}

devops/templates/hello/userlist_work.html
{% extends "./base.html" %}

{% block content %}
<a href="useradd">新增用户</a>
<br>
<br>
<table border="1">
    <thead>
        <tr>
            <th>id</th>
            <th>姓名</th>
            <th>密码</th>
            <th>性别</th>
            <th>管理</th>
    </thead>
<tbody>
    {% for user in users %}
    <tr>
        <td>{{ user.id }}</td>
        <td>{{ user.name }}</td>
        <td>{{ user.password }}</td>
<!--        <td>{{ user.sex }}</td>-->
<!--        代码格式严格，空行不能出错-->
        <td>{% if user.sex == 0 %} 男 {% elif user.sex == 1 %} 女 {% else %} 未定义 {% endif %}</td>
        <td><a href="{% url 'hello:mod' user.id %}">编辑</a>  <a href="{{ user.id }}/delete">删除</a> </td>
<!--        <td><a href="{{ user.id }}/mod">编辑</a>  <a href="{{ user.id }}/delete">删除</a> </td>-->
    </tr>
    {% endfor %}

</tbody>
</table>


{% endblock %}